export const PRODUCT_LIST   = 'PRODUCT_LIST'
export const CART_ADD       = 'CART_ADD'
export const CART_REMOVE    = 'CART_REMOVE'
export const CART_UPDATE    = 'CART_UPDATE'
export const MESSAGE_CHANGE = 'MESSAGE_CHANGE'
